import React from "react";

const Data = [
  {
    id: 1,
    name: "Nasi goreng ayam",
    image: "../src/assets/product/ayam.png",
    categories: "food",
    price: 15000,
    stock: 3,
    isRecommended: false,
  },
  {
    id: 2,
    name: "Nasi goreng babat",
    image: "../src/assets/product/babat.png",
    categories: "food",
    price: 17000,
    stock: 4,
    isRecommended: true,
  },
  {
    id: 3,
    name: "Roti bakar blueberry",
    image: "../src/assets/product/blueberry.png",
    categories: "snack",
    price: 10000,
    stock: 6,
    isRecommended: false,
  },
  {
    id: 4,
    name: "Roti bakar coklat",
    image: "../src/assets/product/coklat.png",
    categories: "desert",
    price: 12000,
    stock: 1,
    isRecommended: true,
  },
  {
    id: 5,
    name: "Nasi goreng gila",
    image: "../src/assets/product/gila.png",
    categories: "food",
    price: 17000,
    stock: 4,
    isRecommended: true,
  },
  {
    id: 6,
    name: "Es goodday",
    image: "../src/assets/product/goodday.png",
    categories: "drink",
    price: 10000,
    stock: 6,
    isRecommended: false,
  },
  {
    id: 7,
    name: "Indomie goreng",
    image: "../src/assets/product/indomie-goreng.png",
    categories: "food",
    price: 15000,
    stock: 3,
    isRecommended: false,
  },
  {
    id: 8,
    name: "Indomie rebus",
    image: "../src/assets/product/indomie-rebus.png",
    categories: "food",
    price: 17000,
    stock: 4,
    isRecommended: false,
  },
  {
    id: 9,
    name: "Es jeruk",
    image: "../src/assets/product/jeruk.png",
    categories: "drink",
    price: 10000,
    stock: 6,
    isRecommended: false,
  },
  {
    id: 10,
    name: "Es Kacang Hijau",
    image: "../src/assets/product/kacang-hijau.png",
    categories: "desert",
    price: 7000,
    stock: 10,
    isRecommended: false,
  },
];

export default Data;
